const randomName = () => {
  const names = [
    "Anal Intruder",
    "Dick Master",
    "King Dingeling",
    "Lana Reversed",
    "MOM",
    "Andy",
    "Party Pooper",
    "Life of the Party",
    "Jokester",
    "Prankster",
    "Jester",
    "Court Fool",
    "Trickster",
    "Fool",
    "Harlequin",
    "Clown",
    "Buffoon",
    "Comedia",
    "Entertainer",
    "Imp",
    "Rapscallion",
    "Scamp",
    "Scoundrel",
    "Rascal",
    "Rogue",
    "Miscreant",
    "Rebel",
    "Renegade",
    "Outlaw",
    "Maverick",
    "Nonconformist",
    "Independent",
    "Free Spirit",
    "Wild One",
    "Adventurer",
    "Explorer",
    "Trailblazer",
    "Pioneerer",
    "Innovator",
    "Disrupter",
    "Game Changer",
    "Rule Breaker",
    "Status Quo Challenger",
    "Change Agent",
    "Trailblazer",
    "Revolutionary",
    "Iconoclast",
    "Game Master",
    "Mastermind",
    "Strategist",
    "Visionary",
    "Leader",
    "Boss",
    "Emperor",
    "King",
    "Queen",
    "Zezima",
  ];
  const randomIndex = Math.floor(Math.random() * (names.length - 1));
  return names[randomIndex];
};

export default randomName;
